### PR TITLE
npm package init

### PR DESCRIPTION
**Pull request by ventilooo**
Now *ringme.js* can be easily embedded in a project  :)

As requested by #7

### CODE REVIEW

**Comment by ssirois** [comment]
Seems fine but testing without publishing on npmjs.scom is hard for me, who has limited knowledge of npm (only a user, not a publisher).

@demirk4n: what do you think of #10

**Comment by ventilooo** [comment]
There it is :
* https://www.npmjs.com/package/ringme.js
_It is temporary under my namespace but it will be later under the organisation **savoirfairelinux**_

**Comment by ssirois** [comment]
I confirm that I was able to use npm to get ringme.js as a dependency of a dummy project.

**Comment by edemirkan** [comment]
Well, I  just checked the ringjs from npm, the code is just a queue implementation in Javascript :)  There's nothing actual ring.js source code related. Hey @ventilooo Are you sure you've not accidentally copy pasted one of your CS assignment? :stuck_out_tongue: 

Here's the source code of the package from npm;
http://pastebin.com/eTdtaVvF

**Comment by ventilooo** [comment]
@demirk4n 
You used the wrong package.
The good one is there:
* https://www.npmjs.com/package/ringme.js

The one you used:
* https://www.npmjs.com/package/ringjs

**Comment by edemirkan** [comment]
Ah, sorry. Yes, "ringme.js" is the correct one.
Just one point. For this to be a valid node module, you need to export it which I saw missing in the code.

`module.exports = RingMe;`

**Comment by ventilooo** [comment]
That's my first node module. I'm not 100% sure on how expose the module. Could you make a PR on this ? :sweat_smile:

**Pull request merged**
