### PR TITLE
Fixes #30, Add ESLint to project

### LINKED ISSUE #30: Add Eslint to the project
### Expected Behaviour
It would be great for maintainability and developers happiness to have lint
Since it's an `Javascript` a simple `.eslintrc` file should be enough !

[Documentation](https://eslint.org/docs/user-guide/configuring)

### Actual Behaviour

There is no lint rules.

### PR DESCRIPTION
**Pull request by Vishwajeetsinh98**
### Changes proposed in this pull request:

* Add .eslintrc.json to project with eslint rules.

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change
```eslint filename```

### Additional notes
If so desired, a pre-commit hook change the package.json like so:

```
"scripts": {
    "lint": "eslint ./ --cache --ignore-pattern .gitignore"
  }, 
"pre-commit": ["lint" ]```

### CODE REVIEW

**Comment by ssirois** [comment]
Welcome to Ringme.js @Vishwajeetsinh98 and thank you for this contribution.

Sadly enough, this issue has already been tackled by @DSchau in #32 

Feel free to check the updated trunk and propose tweaks on ESLint. Be aware that there is also #34 by @nabrahamson in progress.

I would really appreciate if you could _transform_ this PR into a specific _pre-commit hook_ PR. That would be great. Don't forget to document the pre-commit hook inside CONTRIBUTING.md.

**Comment by ventilooo** [comment]
@Vishwajeetsinh98 ping ? could you rebase your work ?

**Comment by Vishwajeetsinh98** [comment]
@ventilooo I don't really think a rebase is required. All I've changed are dependencies and the package.json file.

**Comment by Vishwajeetsinh98** [comment]
@ventilooo I think pulling will be safe.

**Comment by ssirois** [comment]
@Vishwajeetsinh98 OK. I'll take a look and merge this manually.

**Review by ssirois — APPROVED** [review]
I did a manual merge and made sure that `npm run lint` was still running fine. See commit a642087

**Pull request closed without merging**
