### PR TITLE
Fix #29

### LINKED ISSUE #29: Standardize code using ES6 identifier types
### Expected Behaviour

Use `const` type to declare identifiers that should **not** change it's value. If there is no way to keep identifier immutable, use `let` type to declare identifiers that should change it's value and **avoid** using `var` type

This are not rules, but guidelines, use your own judgement to identify the best type for each scenario.

More clarification [here](https://github.com/savoirfairelinux/ringme.js/pull/28#issuecomment-334481198)
### Actual Behaviour
At the moment all identifiers are using `var`

### Steps to reproduce

Just check the source code :smile:

### PR DESCRIPTION
**Pull request by samnegri**
### Changes proposed in this pull request:

Change `var` identifiers to `cosnt`

### Status

- [X] READY
- [ ] HOLD
- [ ] WIP (Work-In-Progress)

### How to verify this change

Check variable declarations

### Additional notes

I did not change `_launchUri`, because it comes from other gist, so I am not sure if it can or should be modified, but I belive this should be separated in another file. Comments about this would be appreciated.

### CODE REVIEW

**Comment by ssirois** [comment]
@peakwinter your modern-JavaScript foo is better than mine. Can you review this? The usage of that `const` keyword in such a way is challenging my experience and reflexes that I've got from other programming languages.

I kind of understand where we want to go and why, but I'm a little overwhelmed. I'll document myself with links that have been provided by @samnegri in the meantime.

**Comment by ssirois** [comment]
@samnegri `_launchUri` is indeed code that has another copyright and license. The license (Expat License) gives us the opportunity to change the code as we do wish so we could change it.

You are right though that this function should be in it's own file. It has been put there for simplicity until we get to the point where this project has a _build script_ that would give us a single minified artifact that would merge everything needed in a single RingMe.js file.

I think that this could also be answered by #8 and https://github.com/savoirfairelinux/angular-ringme.js

**Review by peakwinter — APPROVED** [review]
@samnegri Good job!

@ssirois Yes, these changes are in keeping with modern JS convention. Also, `const` has been supported in all modern browsers for some time (see http://kangax.github.io/compat-table/es6/), which is a common impediment to keep in mind for including non-transpiled ES6 code. 👍

**Comment by ssirois** [comment]
I have manually merge this in order to add credit where it belonged in this team effort.

Thanks to @samnegri, @nabrahamson and @combmag for all the work that gave us the possibility to close this issue rapidly and efficiently.

I will close this PR that have been deprecated by this manual push.

image

**Pull request closed without merging**
