### PR TITLE
[ADD] cute svg + [FIX] typo + [ADD] Readme.md

### PR DESCRIPTION
**Pull request by ventilooo**
@ssirois The svg is here. now find a way to include it in the `container` on his creation.

requested by #3

### CODE REVIEW

**Comment by ssirois** [comment]
@ventilooo What happened to the ringme.js file in this PR?

Can you ignore that file from this "logo" oriented PR or is there something that I have completely missed?

**Comment by ventilooo** [comment]
I've just use a js prettyfier. But yeah, the PR is logo oriented so, I'll remove the js modification.

**Comment by ssirois** [comment]
OK. Feel free to create another pull request for the "prettifying" part.

You could also add in that other pull request an editorconfig file so that other contributors won't break your pretty JS file.

**Comment by ventilooo** [comment]
@ssirois This PR is full for me. waiting for review :tada:

**Review by ssirois — COMMENTED** [review]
I have merge everything but it is always a good idea to clean your branch before proposing a topical PR.

src/ringme.js shouldn't be in this PR.

**Pull request merged**
