### PR TITLE
build: add eslint and linting integration

### LINKED ISSUE #30: Add Eslint to the project
### Expected Behaviour
It would be great for maintainability and developers happiness to have lint
Since it's an `Javascript` a simple `.eslintrc` file should be enough !

[Documentation](https://eslint.org/docs/user-guide/configuring)

### Actual Behaviour

There is no lint rules.

### PR DESCRIPTION
**Pull request by DSchau**
Fixes #30

### Changes proposed in this pull request:

- Adds linting!
- uses eslint-config-standard (but other config--e.g. airbnb, exist as well!)
- Fixes any linting errors

### Status

- [X] READY

### How to verify this change

- Check out project
- run `yarn` or `npm install`
- Run `yarn lint` or `npm run lint` to validate that linting is running, and that linting passes

### Additional notes

- eslint complained about an unnecessary .call (L147-149), so I switched to bind; that said, I don't think you actually need it, but didn't want to break functionality!
- I turned off a rule `brace-style`, but may want to actually look into fixing it at some point
- Some tests would be awesome too :)

### CODE REVIEW

**Comment by ssirois** [comment]
Welcome to ringme.js @DSchau and thank you for this contribution.

I have created a pull request on your branch for grooming stuff suiting your PR (imho). Please consider accepting my PR (https://github.com/DSchau/ringme.js/pull/1) or cherry pick the stuff you prefer over there. After receiving your comments, I'll merge this PR on the trunk (with or without the grooming part, depending on your comments).

I will create an issue about the ESLint rule `brace-style` to make sure we fix this at some point as per your suggestion.

Tests are coming and I hope to be able to bootstrap something by next week with @ventilooo. We will then be able to add this as a contribution guideline!

**Comment by DSchau** [comment]
@ssirois would you be against including a `yarn.lock` file as well? That's about the only other change I would make!

**Comment by DSchau** [comment]
@ssirois also consider using jest :) I can get some basic test scaffolding set up for you guys if you're interested!

**Comment by ssirois** [comment]
@DSchau after reviewing https://github.com/DSchau/ringme.js/pull/2, I think we'll be able to merge this.

A question though, why is there always three different things for the same job in the javascript community? ;) No offense, but couldn't we have choose between `yarn` or `npm` _dependency_/_package_ manager?

I see that @peakwinter was also in favor for this other _lock file_ so I just sent the PR on your branch. I didn't want to postpone this PR more than needed just because I'm not familiar with Javascript projects (as a whole) but I'm still curious! ;)

**Review by ssirois — APPROVED** [review]

**Comment by peakwinter** [comment]
@ssirois Both NPM and Yarn are in fairly widespread usage, so it makes sense to include both files. Essentially one could choose between NPM *and* Yarn (I certainly prefer Yarn), but the best part is that they both use `package.json` and only have custom formats for their particular lock files.

**Pull request merged**
